### ISSUE TITLE
development status now parsed from `setup.json`

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/aiida-ase#16]
In order to remove duplication, we're removing the development status from the aiida plugin registry   and parsing it from the `setup.json` instead.

Just mentioning that on the code registry, the plugin was listed as "stable", while the `setup.json` currently indicates "beta".
https://github.com/aiidaplugins/aiida-ase/blob/322fb8ac3206fe0e0d8af4e982d62c163797f5f5/setup.json#L5

Feel free to close this issue if you're fine with the "beta" status - otherwise please update the `setup.json`.

**Comment by sphuber** [comment]
I have released [v2.0.0](https://pypi.org/project/aiida-ase/) which moves to the `pyproject.toml`. We kept the beta status for now.
