### ISSUE TITLE
Examples need updating

### ISSUE THREAD

**Issue by c-cppx** [aiidateam/aiida-ase#6]
Considering that the ase parser supports selective dynamics and starting magnetization which aiida-vasp does not, it suggest to keep it updated. I encountered problems with the current version and examples which root in deprecated commands e.g:
- ParameterData has not been changed to Dict
- print commands are not python 3 compatible

**Comment by ajjackson** [comment]
As an end-user trying to get this working I am getting stuck on the first example. As well as ParameterData not existing in the DataFactory, I'm getting stuck on `calc = code.new_calc()` as this method doesn't seem to exist. Is that also outdated?

If I try to get a Calculation instance with `CalculationFactory('ase.ase')` I get a `ModuleNotFoundError: No module named aiida.orm.calculation`. I think the JobCalculations need updating to CalcJobs?

I also suggest that the example might use `ase=` to initialise the structure, as ASE/GPAW users are likely to prefer this method!

**Comment by sphuber** [comment]
This plugin is indeed horribly outdated and not compatible with AiiDA v1.0 and up, see issue #4 I will try and see if I can find some time to update the plugin and make it compatible.

**Comment by sthinius87** [comment]
> This plugin is indeed horribly outdated and not compatible with AiiDA v1.0 and up, see issue #4 I will try and see if I can find some time to update the plugin and make it compatible.

I would appreciate this.

**Comment by sphuber** [comment]
> > This plugin is indeed horribly outdated and not compatible with AiiDA v1.0 and up, see issue #4 I will try and see if I can find some time to update the plugin and make it compatible.
> 
> I would appreciate this.

@sthinius87 I have already updated the code base, it just hasn't been released yet. All you need to do is checkout the `develop` branch of this repository and you should be able to use it with AiiDA v1.0 and up
